### ISSUE TITLE
bad package mirror entries in msb repositories

### ISSUE THREAD

**Issue by next-mad-hatter** [mateslackbuilds/msb#15]
At time of writing, "PACKAGE MIRROR" entries in msb repositories point to `http://slackware.org.uk/msb/` as opposed to said repositories' locations -- as in, say, `http://slackware.uk/msb/14.1/1.12/x86_64/`.

This is what breaks `slapt-get` ( see also #9 and #10 ), which is the only package manager I know of to honor the (optional) entry.

**Comment by willysr** [comment]
This is slapt-get's issue, not MSB

**Comment by next-mad-hatter** [comment]
Could you elaborate on that?

To me it seems rather msb's repositories are broken -- I could not find any formal `PACKAGES.TXT`'s format specification, but package managers' (`slapt-get`) and other repositories' (`http://packages.slackonly.com/pub/packages/14.1-x86_64/PACKAGES.TXT`) usage of the entry in question would suggest that it should point to repository's address, not some arbitrary (albeit parent) http location.

If you have any information to the contrary, I will be happy to stand corrected and/or post a slapt-get issue report.

**Comment by willysr** [comment]
it should be like this
http://slackware.uk/msb/14.1/1.12/x86_64/

**Comment by next-mad-hatter** [comment]
What should be -- the entries?  Since they are not.

P.S. I made a hopefully clarifying update to the issue's description, which failed to mention `PACKAGES.TXT`.

**Comment by willysr** [comment]
I updated my gen repo script to the latest version and now it has something like this

PACKAGE NAME:  dconf-0.12.1-i686-1_msb.txz
PACKAGE MIRROR:  http://slackware.org.uk/msb/
PACKAGE LOCATION:  ./14.0/1.6/x86/base

i hope slapt-get developer can take use of this information

**Comment by next-mad-hatter** [comment]
Willy,

this works great for http://slackware.org.uk/msb/PACKAGES.TXT -- the issue still remains with specific repositories, i.e. lists like http://slackware.uk/msb/14.1/1.12/x86_64/PACKAGES.TXT .

br, Max.

**Comment by willysr** [comment]
If you put http://slackware.uk/msb/14.1/1.12/x86_64/ as the mirror URL, and the PACKAGE LOCATION is pointing to base, deps, and extra, it will point to the correct URL to the binary packages

i think this issue should be brought to slapt-get developers, not the repository itself.

**Comment by next-mad-hatter** [comment]
Willy,

could you share any pointers to canonical usage or specification of "PACKAGE MIRROR" entries (or its origins, for that matter)?

E. Hameleers' gen_repos_files.sh, slapt-get documentation and other repositories' usage of the field to me positively suggest that msb repos are broken.

**Comment by next-mad-hatter** [comment]
In case anyone stumbles upon the issue, I'll leave this https://gist.github.com/next-mad-hatter/cca33632b6cceb092220#file-mirror_msb as an external fix proposition.

**Comment by willysr** [comment]
PACKAGE MIRROR is supposed to point to the main URL of the repository and PACKAGE LOCATION is pointing the relative path from the PACKAGE MIRROR URL, so it should be used like this:
"$PACKAGE MIRROR/$PACKAGE LOCATION"

i don't know about slapt-get as i never used them, but slackpkg+ is working fine with this spec and this is how Slackware's PACKAGES.TXT works as well. In fact, Slackware and AlienBOB's repository doesn't contain PACKAGE MIRROR, only PACKAGE LOCATION.

You place the PACKAGE MIRROR's URL to the mirror URL configuration and the tool will parse the PACKAGE LOCATION.

please write this issue to slapt-get developers. We packagers do not really care about the use of third party tools to access our repository since you can easily use rsync to grab all those packages and use installpkg/upgradepkg to install/upgrade from this repository.

**Comment by next-mad-hatter** [comment]
> PACKAGE MIRROR is supposed to point to the main URL of the repository and PACKAGE LOCATION is pointing the relative path from the PACKAGE MIRROR URL, so it should be used like this: "$PACKAGE MIRROR/$PACKAGE LOCATION"

Exactly.  And if you perform, say,
```
curl -s http://slackware.uk/msb/14.1/1.12/x86_64/PACKAGES.TXT | grep -E 'PACKAGE MIRROR|LOCATION' | sort | uniq
```
you will see that the package locations you thus defined don't exist.

> i don't know about slapt-get as i never used them, but slackpkg+ is working fine with this spec and this is how Slackware's PACKAGES.TXT works as well. In fact, Slackware and AlienBOB's repository doesn't contain PACKAGE MIRROR, only PACKAGE LOCATION.

My point was that neither slackpkg+ nor slackpkg make use of PACKAGE MIRROR, in fact I'm pretty certain that slapt-get introduced the entry in the first place and is also the only utility to use it.

> You place the PACKAGE MIRROR's URL to the mirror URL configuration and the tool will parse the PACKAGE LOCATION.

I'm sorry, this makes no sense.

> We packagers do not really care about the use of third party tools to access our repository

Then why add PACKAGE MIRROR to your PACKAGES.TXT? :)

br, m.

**Comment by next-mad-hatter** [comment]
Also see http://software.jaos.org/git/slapt-get/plain/FAQ.html#slgFAQ10 for the entry's description.

**Comment by willysr** [comment]
I'm sorry if my explanation is not very clear previously.
PACKAGE MIRROR is the one in your tool (slapt-get), not the one in the PACKAGES.TXT file
Even Slackware's PACKAGES.TXT doesn't contain PACKAGE MIRROR entry
see http://slackware.osuosl.org/slackware-current/PACKAGES.TXT

If you look at the slackpkg+ configuration file, you will see something like this
msb:           http://slackware.org.uk/msb/{14.0,14.1}/1.6/{x86,x86_64}/
this is what PACKAGE MIRROR is. You define which repository suit you, eg
http://slackware.org.uk/msb/14.1/1.12/x86_64/

then what's parsed from PACKAGES.TXT is the PACKAGE LOCATION, let's say ./base
and then slackpkg+ will download say caja:
http://slackware.uk/msb/14.1/1.12/x86_64/base/caja-1.12.0-x86_64-1_msb.txz

**Comment by next-mad-hatter** [comment]
> Even Slackware's PACKAGES.TXT doesn't contain PACKAGE MIRROR entry

Exactly.  But msb's (or csb's) ones do and the issue is that those fields, while introduced by slapt-get, only being used by slapt-get and, since you add them to your files, obviously intended by you to be interpreted by slapt-get, are broken here insofar that they suggest invalid package urls.

I'm sorry if I cannot think of a way to explain this more clearly than referring to my previous posts.

**Comment by willysr** [comment]
I'm just using script from alienBOB. I don't have any intention with it :)

**Comment by next-mad-hatter** [comment]
There must be a reason why you set DL_URL then :).

**Comment by willysr** [comment]
i thought that entry is used to spesify the base URL and it does, but unfortunately not for sub repository
i can just delete it later and see if it works :)

**Comment by next-mad-hatter** [comment]
Yes, unsetting it would work.  Or setting it to `PACKAGES.TXT`s' proper URLs for each of those files (see slackonly example above).

**Comment by willysr** [comment]
ok, i have removed the PACKAGE MIRROR
should be fixed now

**Comment by next-mad-hatter** [comment]
Thx :)
