### ISSUE TITLE
Glade-3.20.0 compile error with -current updated as of Sept. 29 2017

### ISSUE THREAD

**Issue by mdinslage** [mateslackbuilds/msb#21]
### Master branch

Hi Willy,

I tried compiling the master branch on -current today and glade failed with an error related to use g_ptr_array_find.  I dug around and found  a patch located here 

https://bugzilla.gnome.org/show_bug.cgi?id=782161

After applying the patch I was able to compile glade.  Just a heads up if you want to look into this when you get time.

Thanks.

**Comment by willysr** [comment]
Hi

Thanks for the patch.
It's now applied as 6d47bbfa49b3f12499c502c259aad9a7d57a1c48

**Comment by mdinslage** [comment]
Willy,

Sorry, I should of mentioned, the first diff chunk of that patch causes ./configure to fail.  Removing it and leaving the second part of the patch allows the build to finish with no problems. 

remove this...

```
diff --git a/configure.ac b/configure.ac
index ac59f096..db7487ef 100644
--- a/configure.ac
+++ b/configure.ac
@@ -146,8 +146,10 @@ dnl ================================================================
 dnl Check for gtk+
 dnl ================================================================
 GTK_REQUIRED=3.20.0
+GLIB_REQUIRED=2.53.2
 PKG_CHECK_MODULES([GTK],[
   gtk+-3.0 >= $GTK_REQUIRED
+  glib-2.0 >= $GLIB_REQUIRED
   gmodule-2.0
   libxml-2.0 >= 2.4.0
 ])

```
------------------------------------

**Comment by willysr** [comment]
Thanks again
updated with 69e2f8b
