### ISSUE TITLE
Non responding keyboard on lockscreen

### ISSUE THREAD

**Issue by bad-interpreter** [mateslackbuilds/msb#22]
### Slackware Version
14.2
### MATE Version
1.18
### GIT Branch
14.2-mate-1.18
### Description
Non responding keyboard on lockscreen

Pretty much the same issues as https://forum.manjaro.org/t/mate-lock-screen-not-responding-to-laptop-keyboard-input-after-resume/18123

Keyboard input in password box and in "leave message" box simply doesn't happen!

This is NOT the same behavior if the screen locking is triggered by a timeout (inactivity time): in that case the keyboard input works as expected.

**Comment by willysr** [comment]
I have just tested this on a clean machine and it works as intended

**Comment by bad-interpreter** [comment]
I made some tests. It seems it could be a conky (or something related) issue. If I kill the conky process, I  get the dialogue focus again.
Again, if I kill the mate-screensaver process (it brings me back to the desktop, obviously) and I launch it again, I have no input problems, even if conky is running.

**Comment by willysr** [comment]
it's probably better to push this issue to upstream https://github.com/mate-desktop/mate-screensaver/issues

**Comment by bad-interpreter** [comment]
ok, thanks
