### ISSUE TITLE
msb-build-extra:  building atril-1.24.0 is currently broken

### ISSUE THREAD

**Issue by netrixtardis** [mateslackbuilds/msb#31]
### Slackware Version
slackware64-current:  Sat Feb 22 05:41:50 UTC 2020
### MATE Version
1.24.0
### GIT Branch
master
### Description
building atril-1.24.0 is currently broken:

`configure: error: "SyncTeX support is disabled since library version 1.21 or newer not found"`

Looks like upstream broke this back on Sep 8, 2019 in commit [fe6a855](https://github.com/mate-desktop/atril/commit/fe6a85533ba08ec7ea3f4cee139e10c76363288a).  There is also an open issue with upstream:  [Issue #438](https://github.com/mate-desktop/atril/issues/438)

I'm just opening this issue here so others may know the problem is upstream, and nothing to fix here.  Just for tracking...

**Comment by willysr** [comment]
I will have a look on this in few hours. Last time i test in all my machines and in VM it built just fine

**Comment by netrixtardis** [comment]
a little more research tells me libsynctex is part of TeX Live.  I hope there is a way to make this a standalone package without having to install the full texlive package.

**Comment by netrixtardis** [comment]
Well, It looks like installing texlive resolved my issue.  So, this isn't really an issue.
