### ISSUE TITLE
mate-notification-daemon stops working after a few minutes

### ISSUE THREAD

**Issue by mdinslage** [mateslackbuilds/msb#35]
### Slackware Version
-current (December 15, 2020)
### MATE Version
Master update to date
### GIT Branch
master
### Description

Hi Willy,

I have run into a problem in the last day.  Mate-notifications stop working after a few minutes which causes programs that use them to freeze until the notification times out.  makemkv, thunderbird, network-manager, to name a few.  I am not sure why it seems to work fine when first logging in, but after about a minute or two it just stops.  I opened mate-notification-properties and tested it and got time out errors.  I'll attach screenshots of the errors.  Any help here is appreciated.
![Screenshot at 2020-12-16 02-13-06](https://user-images.githubusercontent.com/28424337/102322169-42719c80-3f44-11eb-9b34-8ccf3599fb9b.png)
![Screenshot at 2020-12-16 01-49-34](https://user-images.githubusercontent.com/28424337/102322187-469dba00-3f44-11eb-8b9c-803928441ac2.png)

**Comment by willysr** [comment]
i have rebuilt mate-notification-daemon several times to find a solution for this
which build did you have in your machine?

**Comment by mdinslage** [comment]
Right now build 3, I can't seem to find what is killing the daemon.  After I restart it and everything is fine, but then it dies again.

**Comment by mdinslage** [comment]
Possibly relate here?: https://github.com/mate-desktop/mate-notification-daemon/issues/184

**Comment by willysr** [comment]
So basically it's a race condition on who got the dbus session since there's only 1 dbus name for all DE.
What i did is to add cron entry to run mate-notification-daemon -r to replace existing dbus with mate-notification-daemon

**Comment by willysr** [comment]
this is an old bug issue: https://bugzilla.redhat.com/show_bug.cgi?id=1490959

**Comment by mdinslage** [comment]
I am reading up on it, so If I am understanding it correctly, plasma5 and mate are basically tripping over each other for notify-impl?

**Comment by mdinslage** [comment]
As a temporary workaround, I renamed /usr/share/dbus-1/services/org.kde.plasma.Notifications.service to /usr/share/dbus-1/services/org.kde.plasma.Notifications.service.old.  Probably not the best solution, but I don't have any plans to use KDE5 so this should suffice.

**Comment by mdinslage** [comment]
Willy I did see this https://bugzilla.redhat.com/show_bug.cgi?id=484945#c40.  I will look more into this tomorrow.

**Comment by willysr** [comment]
That's why i put a cron job and a desktop file to be started when it's loaded so it replace the current notification daemon available by issuing mate-notification-daemon -r

**Comment by willysr** [comment]
i have Plasma 5 and MATE and it works fine here with BUILD 3

**Comment by mdinslage** [comment]
This might just be specific to my machine then, when the daemon stops after 30 seconds of inactivity it just wont come back.  Getting plasma notifications out of the way fixes it.  I'll mark this as solved since I can workaround it.  I will test what I read in the above post and if renaming the plasma notification won't break KDE I may ask pat to issue a patch.
