### ISSUE TITLE
eom and a few others fail to build with same error

### ISSUE THREAD

**Issue by mdinslage** [mateslackbuilds/msb#38]
### master

After today's -current that dropped back down to python 3.9 I decided to rebuild the whole mate set of packages.  However I am getting build failures on a few packages with the same error.  Here is the output.

```
  GEN    ko/
  GEN    ku/
  GEN    ky/
  GEN    lt/
  GEN    lv/
  GEN    mai/
Warning: Could not merge ja translation for msgid:
b'To view all the directory images in fullscreen, choose <menuchoice> <guimenu>View</guimenu><guimenuitem>Full Screen</guimenuitem> </menuchoice> or press <keycap>F11</keycap>. To view them as a slide show, choose <menuchoice><guimenu>View</guimenu><guimenuitem>Slideshow</guimenuitem></menuchoice> or press <keycap>F5</keycap>. To return to the collection view, press the <keycap>Esc</keycap> key, or <keycombo><keycap>Ctrl</keycap><keycap>W</keycap></keycombo>. For more information about how to customize the slide show, see <xref linkend="eom-prefs-slideshow"/>.'
make[2]: *** [Makefile:608: ja/ja.stamp] Error 139
make[2]: *** Waiting for unfinished jobs....
  GEN    mk/
make[2]: Leaving directory '/tmp/msb/eom-1.26.0/help'
make[1]: *** [Makefile:539: all-recursive] Error 1
make[1]: Leaving directory '/tmp/msb/eom-1.26.0'
make: *** [Makefile:465: all] Error 2
```

I also tested this on a VM with last weeks -current that still had python 3.10 and it also had this same error.

Any help here is appreciated. 

Thanks

**Comment by mdinslage** [comment]
I was able to isolate the problem to this change in -current on Oct. 23
```
ap/itstool-2.0.7-x86_64-2.txz:  Rebuilt.
  Rebuilt with PYTHON=/usr/bin/python3. Thanks to USUARIONUEVO.
```
Rebuilding itstool to use python2 fixes building of eom.  Probably the other packages too, will test that shortly.   Not sure why building it against python3 is causing the issue.  If I find more answers I'll report back here.

**Comment by mdinslage** [comment]
I got it to compile, after looking around I found this patch for libxml2 [here](https://bugzilla.opensuse.org/attachment.cgi?id=746044).  After recompiling libxml2 with that patch then recompiling itstool with python3, eom finishes cleanly.

**Comment by willysr** [comment]
Thanks, let's wait for Patrick to rebuilt libxml2

**Comment by mdinslage** [comment]
Pat fixed libxml2.  I just compiled all the packages to test and it works fine now.  Will close this.
