### ISSUE TITLE
mate-utils-1.26.1 needs this patch to build

### ISSUE THREAD

**Issue by mdinslage** [mateslackbuilds/msb#41]
### GIT Branch - master

Hi Willy,
I am getting a little ahead but I thought I would upgrade a few of the mate packages to their latest 1.26.x releases.  I ran into a compile error with mate-utils-1.26.1 but I found a patch that fixes the issue.  I just thought I would report to save you time if you ran into the same issue.

Link to patch
https://salsa.debian.org/debian-mate-team/mate-utils/-/raw/master/debian/patches/1001_fix-gsearchtool-pt-help-translation.patch

**Comment by willysr** [comment]
hi @mdinslage 

master branch is used for -current only and it works just fine in current here

**Comment by willysr** [comment]
Fixed as in 00c77be

**Comment by mdinslage** [comment]
Thanks Willy. The master has been compiling fine on 15.0 with libsoup3 from SBo.  I wasn't thinking and should of tested it on -current before I reported since I know master on 15.0 is an unsupported setup.  Thanks for adding the patch though :).

**Comment by willysr** [comment]
it's fine, i tested on -current for master but since there's no new releases that can't be satisfied by 15.0, i guess i can still support 1.26.x longer in 15.0
