### ISSUE TITLE
A few build failures with GCC-14

### ISSUE THREAD

**Issue by mdinslage** [mateslackbuilds/msb#46]
### GIT Branch - master

Willy, the following packages are failing with gcc 14 in current.  
pangox-compat
murrine
rarian

pangox-compat just needs the following as a workaround
CFLAGS="$SLKCFLAGS -fpermissive" 

patch for murrine
https://src.fedoraproject.org/rpms/gtk-murrine-engine/raw/e3f6ab3d10f3124353ace08471dd42b87af76399/f/gtk-murrine-engine-c99.patch

rarian I just upgraded the package to version 0.8.5 and it built fine, doing that does add tinyxml as a new dependency.

**Comment by willysr** [comment]
thanks, this should be fixed by acc22303db93dbecc630e4794c0e810fac6de325, 1861fc291f004937aadff0d069a0027e2485d756, 3a9266c0c926317c0e657b04a2efef6576ba277b, and c395446c0e36e7030539e8e984edd2b579115778
