### ISSUE TITLE
caja-actions FTBFS on current

### ISSUE THREAD

**Issue by mdinslage** [mateslackbuilds/msb#47]
### GIT Branch = master

Willy,

I ran into a build error with caja-actions I tracked down the problem to itstool.  Looks like it needs this PR patch.  After applying the patch caja-actions builds fine.  If you get a chance would you test on your end and confirm my findings.  If there is a better way to fix this please let me know.  If you can confirm the build failure and can't find another fix then perhaps we should ask Pat to add the patch to itstool?

https://github.com/itstool/itstool/pull/47

**Comment by willysr** [comment]
hi @mdinslage

Thanks for reporting.
I can confirm the build failure and after applying above patch to itstool and build it myself, i can also confirm that this issue is fixed.

Let's hope Pat agreed to patch itstool

**Comment by willysr** [comment]
Pat patched it on current, so closing this issue
thanks
