### ISSUE TITLE
(pluma:17250): GLib-GIO-ERROR **: Settings schema 'org.mate.pluma' is not installed

### ISSUE THREAD

**Issue by timcowchip** [mateslackbuilds/msb#5]
org.mate.pluma.gschema.xml: Error on line 7 char 31: attribute 'xml:lang' invalid for element 'summary'.  This entire file has been ignored.
rm org.mate.pluma.gschema.xml.in

I am using slackware64-14.1 so gtksourceview is from /deps directory.

**Comment by willysr** [comment]
This has been tracked upstream: https://github.com/mate-desktop/pluma/issues/107

**Comment by wazoox** [comment]
I've left a workaround in comments upstream https://github.com/mate-desktop/pluma/issues/107

**Comment by willysr** [comment]
> I've left a workaround in comments upstream mate-desktop/pluma#107

Yes, i noticed that
Thank you and i will try this solution asap :)



-- 
Willy Sudiarto Raharjo
Personal Blog : http://willysr.blogspot.com
Linux Blog: http://slackblogs.blogspot.com

**Comment by willysr** [comment]
This has been fixed in bc3211240b3509686b8932fd23bffbeedb8d2bae
