### ISSUE TITLE
gupnp-0.20.13 doesn't build on 14.1

### ISSUE THREAD

**Issue by idlemoor** [mateslackbuilds/msb#9]
gupnp-0.20.13 doesn't build on 14.1 because the 14.1 version of libsoup is too old. I guess everybody else is using -current :-(

configure: error: Package requirements (glib-2.0 >= 2.28.0                             gio-2.0                             gmodule-2.0                             gssdp-1.0 >= 0.13.0                             libsoup-2.4 >= 2.48.0                             libxml-2.0                             uuid) were not met:

Requested 'libsoup-2.4 >= 2.48.0' but version of libsoup is 2.42.2

**Comment by willysr** [comment]
Please use 14.1-mate-1.10 branch for building in 14.1

**Comment by idlemoor** [comment]
Ok, thanks, sorry I missed that :-(

**Comment by timcowchip** [comment]
On Thu, 18 Jun 2015 05:00:22 -0700
Willy Sudiarto Raharjo <notifications@github.com> wrote:

> Please use 14.1-mate-1.10 branch for building in 14.1
> 
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/mateslackbuilds/msb/issues/9#issuecomment-113130030
 I ran into the same issue on 14.1, The build from git also hiccuped at
libgksu. I ended up installing from
http://slackware.org.uk/msb/14.1/1.10/x86_64/deps/libgksu-2.0.12-x86_64-3_msb.txz.

I had to download the packages and use installpkg. Slapt-get didn't
work for some reason: 

 The following packages will be upgraded:
  eom mate-utils 
2 upgraded, 0 reinstalled, 0 newly installed, 0 to remove, 3 not upgraded.
Need to get 1.7MB of archives.
After unpacking 150.0kB of additional disk space will be used.
Do you want to continue? [y/N] y
1/2 Get http://slackware.org.uk/msb/ eom 1.10.2-x86_64-1_msb
[700.0kB]...Failed to download: HTTP response code said error

**Comment by willysr** [comment]
AFAIK, libgksu was never changed since it's inclusion in 1.8, so it should be working on 14.1
i never tested with slapt-get. I used to try using sbopkg+ and it does work, but never tested on 1.10 actually.

Looking at your slapt-get message, it seems that it point to the wrong URL
